pipeline {
	agent any
	stages {
		steps {
			stage ('Test') {
				dir('project') {
					script {
						timeout(20) {
							sh '''/bin/bash jenkins/jenkins_script.sh'''
						}
					}
				}
			}
		}
	}
}
